In [1]:
import numpy as np

In [3]:
list1=[1,2,3]
print(list1)
print(type(list1))

[1, 2, 3]
<class 'list'>


In [11]:
array1 = np.array(list1)
print(type(array1))
print(array1.shape)

array2=np.array([[1,2,3],[4,5,6]])
print(array2)
print(type(array2))

array3 = np.array([[1,2,3]])
print(array3)
print(type(array3))

<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[1 2 3]]
<class 'numpy.ndarray'>


In [14]:
array1= np.array([1,2,3])
print(type(array1))
print(array1.shape)

array2=np.array([[1,2,3],[4,5,6]])
print(type(array2))
print(array2.shape)

array3=np.array([[1,2,3]])
print(type(array3))
print(array3.shape)


<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [17]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))


array1: 1차원, array2: 2차원, array3:  2차원


In [18]:
list1=[1,2,3]
print(type(list1))

array1=np.array(list1)
print(array1,array1.dtype)

<class 'list'>
[1 2 3] int32


In [19]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3)


['1' '2' 'test'] <U11
[1. 2. 3.]


In [21]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')

[1. 2. 3.] float64


In [22]:
array2=np.array([[1,2,3],[4,5,6]])
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [23]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [25]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [27]:
array1=np.arange(10)
print(array1)

array2=array1.reshape(2,5)
print(array2)

array3=array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
array1=np.arange(5)
array2d_1=array1.reshape(-1,1)
print(array1)
print(array2d_1)

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [31]:
array1=np.arange(start=1,stop=10)
print(array1)
    
value=array1[2]
print(value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>


In [33]:
print(array1[-1])
print(array1[-2])

9
8


In [36]:
array1d=np.arange(start=1,stop=10)
array2d=array1.reshape(3,3)
print(array2d)
print(array2d[0,0])
print(array2d[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2


In [37]:
array1=np.arange(start=1,stop=10)
print(array1)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [40]:
array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [47]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print(array2d[0:2,0:2])
print(array2d[1:3,0:3])
print(array2d[1:3,:])
print(array2d[:,:])
print(array2d[:2,1:])
print(array2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


In [54]:
array1d=np.arange(start=1,stop=10)
array2d= array1d.reshape(3,3)
print(array2d)

array3=array2d[[0,1],2]
print(array3)

array4=array2d[[0,2],0:2]
print(array4)

array5=array2d[[0,1]]
print(array5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [7 8]]
[[1 2 3]
 [4 5 6]]


In [55]:
array1d=np.arange(start=1,stop=10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [57]:
print(array1d>5)

var1=array1d>5
print(var1)
print(type(var1))

[False False False False False  True  True  True  True]
[False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [58]:
print(array1d)
array3=array1d[array1d>5]
print(array3)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [63]:
array1d=np.arange(start=1,stop=10)
boolean_indexes = np.array([False,False,True,False,False,False,False,False,False])
array3=array1d[boolean_indexes]
print(array3)

[3]


In [64]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print(array4)


[6 7 8 9]


In [66]:
print(array1d[array1d>5])

[6 7 8 9]


In [67]:
org_array=np.array([3,1,9,5])
print(org_array)

[3 1 9 5]


In [72]:
org_array=np.array([3,1,9,5])
print(org_array)

sort_array1=np.sort(org_array)#np.array이용 
print(sort_array1)
print(org_array) #오리지널은 그대로

org_array.sort() #ndarray.sort이용 -> original바군다 
print(org_array)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
[1 3 5 9]


In [77]:
org_array=np.array([3,1,9,5])
sort_array1_dsc=np.sort(org_array)[::-1]
print(sort_array1_dsc)

[9 5 3 1]


In [80]:
array2d=np.array([[8,12],[7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0)
print(sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d,axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [83]:
org_array=np.array([3,1,9,5])
print(np.sort(org_array)[::-1])

sort_indices_desc=np.argsort(org_array[::-1]) ##argsort -> 인덱스출력하는 함수
print(sort_indices_desc)

[9 5 3 1]
[2 3 0 1]


In [ ]:
name_array=np.array(['john','mike','df','dff'])
score_array=

In [88]:
A=np.array([[1,3],[3,5]])
B=np.array([[2,3,4],[2,3,4]])
dot_product=np.dot(A,B)
print(dot_product)

[[ 8 12 16]
 [16 24 32]]


In [89]:
A=np.array([[1,2],[3,4]])
print(np.transpose(A))

[[1 3]
 [2 4]]
